before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/qb
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
